### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KEANO89** [simonmartyr/picnic-api#3]
Since you published the code publicly on Github, I assume that you are interested in allowing others to use your project. However, there isn't a license specified currently. As a side effect the automatic documentation by [pkg.go.dev](https://pkg.go.dev/github.com/simonmartyr/picnic-api) does not work.

Personally I'd recommend MIT, Apache or MPL, but in case you're unsure about it [choosealicense.com](https://choosealicense.com/) might be helpful.

Thanks for considering and your work here.

**Comment by simonmartyr** [comment]
Hi @KEANO89 
Thanks for reaching out and showing an interest. 
You are completely right, I've now included a license. 

Thanks again.
